name: Cocoapods Release

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
  set-user-agent:
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Publish to CocoaPods trunk
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push reown-swift.podspec --verbose --allow-warnings
